version: '2.2'

services:

  postgres:
    image: postgres:15.1-alpine
    container_name: dataset-parser-postgres
    environment:
      APP_ENV: dev
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: geomatrix
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "54325:5432"

volumes:
  postgres:
